---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: a11y-dashbord-connector-pa11y
spec:
  concurrencyPolicy: Forbid
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pa11y
            image: registry.zeit.de/a11y-dashbord-connector:v0.1
            command:
            - npm
            - run
            - pa11y
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: a11y-dashbord-connector-cssstats
spec:
  concurrencyPolicy: Forbid
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cssstats
            image: registry.zeit.de/a11y-dashbord-connector:v0.1
            command:
            - npm
            - run
            - cssstats
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: a11y-dashbord-connector-htmlvalidator
spec:
  concurrencyPolicy: Forbid
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: htmlvalidator
            image: registry.zeit.de/a11y-dashbord-connector:v0.1
            command:
            - npm
            - run
            - htmlvalidator
          restartPolicy: OnFailure
