---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: frontend-monitoring-pa11y
spec:
  concurrencyPolicy: Forbid
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pa11y
            image: eu.gcr.io/zeitonline-210413/frontend-monitoring:v0.1
            command:
            - npm
            - run
            - pa11y
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: frontend-monitoring-cssstats
spec:
  concurrencyPolicy: Forbid
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cssstats
            image: eu.gcr.io/zeitonline-210413/frontend-monitoring:v0.1
            command:
            - npm
            - run
            - cssstats
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: frontend-monitoring-htmlvalidator
spec:
  concurrencyPolicy: Forbid
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: htmlvalidator
            image: eu.gcr.io/zeitonline-210413/frontend-monitoring:v0.1
            command:
            - npm
            - run
            - htmlvalidator
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: frontend-monitoring-homepagestats
spec:
  concurrencyPolicy: Forbid
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: homepagestats
            image: eu.gcr.io/zeitonline-210413/frontend-monitoring:v0.1
            command:
            - npm
            - run
            - homepagestats
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: frontend-monitoring-adplaces
spec:
  concurrencyPolicy: Forbid
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: adplaces
            image: eu.gcr.io/zeitonline-210413/frontend-monitoring:v0.1
            command:
            - npm
            - run
            - adplaces
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: frontend-monitoring-unused-css-js
spec:
  concurrencyPolicy: Forbid
  schedule: "*/55 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: unused-css-js
            image: eu.gcr.io/zeitonline-210413/frontend-monitoring:v0.1
            command:
            - npm
            - run
            - unused-css-js
          restartPolicy: OnFailure
